#name: For Test
#on: [push]
name: Scheduled
on:
  schedule:
    # 월화수목금 9~18시에 한시간마다 실행
    # UTC의 09:00는 한국시간 18:00
    - cron: '0 0-23/1 * * 1-5'
jobs:
  tesla:
    name: Tesla
    runs-on: ubuntu-latest
    steps:
      - name: Tesla stock
        id: tesla
        uses: strong-gemi/action-alphavantage-time-series-stock-api@master
        with:
          function: 'GLOBAL_QUOTE'
          symbol: 'TSLA'
      - uses: 8398a7/action-slack@v3
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'tesla종가',
              icon_emoji: ':octocat:',
              attachments: [{
                color: '${{ job.status }}' === 'success' ? 'good' : '${{ job.status }}' === 'failure' ? 'danger' : 'warning',
                text: `price - ${{ steps.tesla.outputs.GQ-price }}`,
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TLSA_SLACK_WEBHOOK_URL }}