name: For Test
on: [push]
#name: Scheduled3
#on:
#  schedule:
#    # 월화수목금 9~18시에 한시간마다 실행
#    # UTC의 09:00는 한국시간 18:00
#    - cron: '0 09-17/1 * * 1-5'
jobs:
  tesla:
    name: Tesla
    runs-on: ubuntu-latest
    steps:
      - name: Tesla stock
        id: tesla
        uses: strong-gemi/action-alphavantage-time-series-stock-api@master
        with:
          function: 'GLOBAL_QUOTE'
          symbol: 'TSLA'
      - uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.TLSA_SLACK_WEBHOOK_URL }}
        with:
          status: custom
          fields: workflow,job,commit,repo,ref,author,took
          custom_payload: |
            {
              username: 'tesla종가',
              icon_emoji: ':octocat:',
              blocks: [{
                type: 'actions',
                elements: [{
                  type: "button",
                  text: {
                    type: "plain_text",
                    emoji: true,
                    text: "Approve"
                  },
                  style: "primary",
                  value: "click_me_123"
                },{
                  type: "button",
                  text: {
                    type: "plain_text",
                    emoji: true,
                    text: "Deny"
                  },
                  style: "danger",
                  value: "click_me_123"
                }]
              }]
            }